project_id = "bkitraqfgcbahsfkqsxx"

[functions.match-alerts]
enabled = true
verify_jwt = false
import_map = "./functions/match-alerts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/match-alerts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/match-alerts/*.html" ]

[functions.ai-tournament-updater]
enabled = true
verify_jwt = false
import_map = "./functions/ai-tournament-updater/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-tournament-updater/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-tournament-updater/*.html" ]

[functions.extract-match-stats]
enabled = true
verify_jwt = false
import_map = "./functions/extract-match-stats/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/extract-match-stats/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/extract-match-stats/*.html" ]

[functions.auto-extract-matches]
enabled = true
verify_jwt = false
import_map = "./functions/auto-extract-matches/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/auto-extract-matches/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/auto-extract-matches/*.html" ]
